forum:
    resource: "@ForumBundle/Resources/config/routing.yml"
    prefix:   /forum


faq:
    resource: "@FaqBundle/Resources/config/routing.yml"
    prefix:   /faq
back:
    resource: "@UserBundle/Resources/config/routing.yml"
    prefix:   /back
front:
    resource: "@UserBundle/Resources/config/routing.yml"
    prefix:   /
fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

app:
    resource: '@AppBundle/Controller/'
    type: annotation
