back:
    resource: "@BackBundle/Resources/config/routing.yml"
    prefix:   /back

mgilet_notification:
    resource: "@MgiletNotificationBundle/Controller/"
    prefix: /notifications

service:
    resource: "@ServiceBundle/Resources/config/routing.yml"
    prefix:   /service

forum:
    resource: "@ForumBundle/Resources/config/routing.yml"
    prefix:   /forum

user:
    resource: "@UserBundle/Resources/config/routing.yml"
    prefix:   /

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

app:
    resource: '@AppBundle/Controller/'
    type: annotation
