
forum_disply:
    path:     /disply
    defaults: { _controller: ForumBundle:Forum:index    }

forum_create:
    path:     /create
    defaults: { _controller: ForumBundle:Forum:create    }

forum_show:
    path:     /{id}
    defaults: { _controller: ForumBundle:Forum:show    }